name: Build

on: pull_request

jobs:
  quality-checks:
    concurrency:
      group: monorepo-plugin-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.1'
          cache: true

      - uses: KengoTODA/actions-setup-docker-compose@v1
        with:
          version: '2.14.2' # the full version of `docker-compose` command

      - name: Check quality
        run: make quality

      - name: Run tests
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
